# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformInstaller@0
  displayName: 'TF_Install'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'S2-SPN-DevOps001'
    backendAzureRmResourceGroupName: 'S2-RG-DevOps42'
    backendAzureRmStorageAccountName: 's2storageaccountdevops42'
    backendAzureRmContainerName: 's2containerdevops42'
    backendAzureRmKey: 'DevOps001-main.tf'